### PR TITLE
Binary directory

### PR DESCRIPTION
**Pull request by silverdr**
- dir created
- .gitkeep added
- release 1.0 added

### CODE REVIEW

**Comment by Borszczuk** [comment]
Could we have version number separated from the name, i.e. `vbasic_1.0.c64` for better readability? Also please use standard `.prg` name suffix.

**Review by Borszczuk — CHANGES_REQUESTED** [review]
1. Please stick to standard `.prg` name suffix only and strip `.c64` as it adds no value.
1. Could we have version number separated from the name, i.e. `vbasic_1.0.prg` for better readability?
1. Do we need `.gitkeep` if there's already 1.0 release binary?

**Comment by silverdr** [comment]
@1 - Well, it does. No matter what some people say ;-)
@2 - No, the underscore does not translate well into CBM charset, which doesn't have any direct equivalent. There are workarounds with PETSCII, and dynamic translation but that's a nuissance
@3 - technically it is not _required_. Just common practice, forcing a conscious action for directory removal, if files get temporarily (or not temporarily) removed

**Comment by Borszczuk** [comment]
I am fine with @2 and @3 then. But as for @1 lets @laubzega decide.

**Comment by Borszczuk** [comment]
After a thought - there's no point of adding release binary to the source repository. Compiled binary is already part of release here: https://github.com/madhackerslab/beamracer-vbasic/releases therefore I am voting to reject this PR.

**Comment by laubzega** [comment]
> After a thought - there's no point of adding release binary to the source repository. Compiled binary is already part of release here: https://github.com/madhackerslab/beamracer-vbasic/releases therefore I am voting to reject this PR.

But "releases" will only hold the official numbered releases. bin/ on the other hand is supposed to be updated with every repo checkin, so that users can experience the joy of fresh code without building it themselves.

**Review by laubzega — APPROVED** [review]
Discussed f2f with @silverdr. Approved.

**Comment by MarcinOrlowski** [comment]
Releases can hold anything you want. The point is that putting final binary into the source code repository it was built from is really odd and bad idea/practice. You want nightly or so, then let's go for it but **proper** way, w/o bloating **source repo** without a real reason.

**Comment by silverdr** [comment]
FWIW - I added that binary on explicit request by Miłek as I didn't see it being so much a bad idea but now I think I didn't understand one of his objectives so we probably need to do a short call to clarify.

**Pull request merged**
